# Generated by Django 5.2.15 on 2026-06-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                ("capacity", models.PositiveIntegerField(verbose_name="Capacidad")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ubicación"
                    ),
                ),
                (
                    "amenities",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Servicios"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sala",
                "verbose_name_plural": "Salas",
                "ordering": ["name"],
            },
        ),
    ]
